export enum ErrorCode {
  INTERNAL_ERROR = 'INTERNAL_ERROR',
  VALIDATION_ERROR = 'VALIDATION_ERROR',
  NOT_FOUND = 'NOT_FOUND',
  UNAUTHORIZED = 'UNAUTHORIZED',
  FORBIDDEN = 'FORBIDDEN',
  BAD_REQUEST = 'BAD_REQUEST',
  CONFLICT = 'CONFLICT',

  // Billing error codes
  SUBSCRIPTION_NOT_FOUND = 'SUBSCRIPTION_NOT_FOUND',
  PLAN_NOT_FOUND = 'PLAN_NOT_FOUND',
  PLAN_PRICE_NOT_FOUND = 'PLAN_PRICE_NOT_FOUND',
  ADDON_NOT_FOUND = 'ADDON_NOT_FOUND',
  INVALID_SUBSCRIPTION_STATUS = 'INVALID_SUBSCRIPTION_STATUS',
  ADDON_PURCHASE_RESTRICTED = 'ADDON_PURCHASE_RESTRICTED',
  INSUFFICIENT_CREDITS = 'INSUFFICIENT_CREDITS',
  STRIPE_API_ERROR = 'STRIPE_API_ERROR',
  WEBHOOK_SIGNATURE_INVALID = 'WEBHOOK_SIGNATURE_INVALID',
  DUPLICATE_PLAN_SLUG = 'DUPLICATE_PLAN_SLUG',
  DUPLICATE_BILLING_INTERVAL = 'DUPLICATE_BILLING_INTERVAL',
  CANNOT_DEACTIVATE_LAST_PRICE = 'CANNOT_DEACTIVATE_LAST_PRICE',
}
